spring:
  datasource:
    url: jdbc:mysql://web-service-db.cnwckavej6dv.us-east-2.rds.amazonaws.com:3306/webservicedb
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

liquibase:
  databaseChangeLogTableName: DATABASECHANGELOG
  changeLogFile: classpath:/db/changelog/changelog.xml
  url: jdbc:mysql://web-service-db.cnwckavej6dv.us-east-2.rds.amazonaws.com:3306/webservicedb
  username: ${database.username}
  password: ${database.password}

server:
  ssl:
    key-store: certs/springboot.p12
    key-store-password: springboot
    key-password: springboot
    enabled: true

logging:
  level:
    root: INFO

scheduler:
  enabled: true