server:
  port: 8080

spring:
  config:
    import: optional:classpath:apikeys.yml

logging:
  level:
    org:
      springframework:
        boot:
          context:
            config:
              ConfigFileApplicationListener: info