spring:
  config:
    import:
      file:secrets/apikeys.yml, file:secrets/admin-keys.yml, app-metadata.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

springdoc:
  packagesToScan: io.github.johnchoi96.webservice
  swagger-ui:
    path: /api-docs

server:
  port: 8080

gcp:
  firebase:
    serviceAccount: secrets/firebase-service-account.json

logging:
  file:
    name: web-service-application.log