server:
  ssl:
    key-store: certs/springboot.p12
    key-store-password: springboot
    key-password: springboot
    enabled: true

logging:
  level:
    root: INFO

scheduler:
  enabled: true

gcp:
  firebase:
    serviceAccountPath: /home/ec2-user/secrets/firebase-service-account.json