server:
  ssl:
    key-store: certs/springboot.p12
    key-store-password: springboot
    key-password: springboot
    enabled: true

logging:
  level:
    root: DEBUG  # ERROR, WARN, INFO, DEBUG, or TRACE.

scheduler:
  enabled: true

gcp:
  firebase:
    serviceAccountPath: secrets/firebase-service-account.json