spring:
  config:
    import:
      file:secrets/apikeys.yml, file:secrets/admin-keys.yml, file:secrets/datasource.yml, file:secrets/ellie.yml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

springdoc:
  packagesToScan: com.johnchoi96.webservice
  swagger-ui:
    path: /api-docs

server:
  port: 8080

gcp:
  firebase:
    serviceAccount: secrets/firebase-service-account.json
  drive:
    serviceAccount: secrets/google-drive-service-account.json

logging:
  file:
    name: web-service-application.log