spring:
  config:
    import:
      file:secrets/apikeys.yml, file:secrets/admin-keys.yml, app-metadata.yml

server:
  port: 8080

gcp:
  firebase:
    serviceAccount: secrets/firebase-service-account.json

logging:
  file:
    name: web-service-application.log