name: Deploy-To-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

env:
  ssh_key: ${{ secrets.EC2_SSH_KEY }}

jobs:
  build:
    name: Build executable jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      #      - name: Copy ssh key
      #        run: mkdir .ssh && echo $ssh_key >> .ssh/id_rsa
      - name: list stuff
        run: ls -al && pwd && ls -al ./target
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        with:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST_DNS }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
          source: './target/web-service-0.0.1-SNAPSHOT.jar'
          target: '~/'
          overwrite: true
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/ec2-user/SampleExpressApp"
#          SCRIPT_AFTER: |
#            killall java &&
#            java -jar web-service-0.0.1-SNAPSHOT.jar &
