name: Deploy-To-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build executable jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
  upload:
    name: SCP files to server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: list
        run: ls -al && pwd
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        with:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
          source: './target/web-service-0.0.1-SNAPSHOT.jar'
          target: '~/'
          overwrite: true
  deploy:
    name: SSH and start the app
    needs: [ build, upload ]
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SCRIPT_AFTER: |
            java -jar web-service-0.0.1-SNAPSHOT.jar &

