name: Tests

# Trigger deployment on push and PR to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Unit Tests and Application Startup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Unit Tests
        run: mvn test

      - name: Create dummy yml files
        run: |
          mkdir secrets/
          cp src/test/resources/admin-keys.yml secrets/
          cp src/test/resources/apikeys.yml secrets/
          cp src/test/resources/datasource.yml secrets/

      - name: Start Application
        run: |
          java -jar target/web-service-0.0.1-SNAPSHOT.jar &
          echo $! > app_pid.txt

      - name: Wait for Application to Start
        run: sleep 10

      - name: Verify Application is Running
        run: |
          curl --retry 10 --retry-delay 5 --fail http://localhost:8080/actuator/health

      - name: Stop Application
        run: |
          kill $(cat app_pid.txt)
          rm app_pid.txt
          rm -rf secrets/